version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AthenaAwsCmdbConnectorTest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1viuglzvpjcqs"
s3_prefix = "AthenaAwsCmdbConnectorTest"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AthenaCatalogName=\"aws-cmdb\" SpillBucket=\"repo.sam.597377428377\" SpillPrefix=\"athena-spill\" LambdaTimeout=\"900\" LambdaMemory=\"3008\" DisableSpillEncryption=\"false\""
